#!/bin/bash

# ~/ files
stow -R tmux/
stow -R bash/
stow -R vim/

# config folders
cd ~/.config/
ln -s ../.Dotfiles/nvim/
ln -s ../.Dotfiles/kitty/
ln -s ../.Dotfiles/fancy-cat
ln -s ../.Dotfiles/yabai
ln -s ../.Dotfiles/skhd
ln -s ../.Dotfiles/neofetch
