#!/bin/bash
# pushd $DOTFILES
cd ~/
ln -s .../.Dotfiles/bash/
ln -s .../.Dotfiles/tmux/
ln -s .../.Dotfiles/vim/
cd ../.config/
ln -s ../.Dotfiles/nvim/
ln -s ../.Dotfiles/kity/
ln -s ../.Dotfiles/fancy-cat
# popd
