#!/bin/bash
# pushd $DOTFILES
cd ~/
cp .Dotfiles/bash/.profile ./.profile
cp .Dotfiles/bash/.bashrc ./.bashrc
cp .Dotfiles/tmux/.tmux.conf ./.tmux.conf
cp .Dotfiles/vim/.vimrc ./.vimrc

cd ~/.config/
ln -s ../.Dotfiles/nvim/
ln -s ../.Dotfiles/kitty/
ln -s ../.Dotfiles/fancy-cat
ln -s ../.Dotfiles/yabai
ln -s ../.Dotfiles/skhd
ln -s ../.Dotfiles/neofetch
# popd
